# Supabase CLI configuration. Doc: https://supabase.com/docs/reference/cli/config
project_id = "tsdpbqcwjckbfsdqacam"

[db]
major_version = 15

[db.migrations]
schema_paths = []

[functions.provision-user-start]
verify_jwt = true

[functions.provision-user-check]
verify_jwt = true

[functions.provision-user-finalize]
verify_jwt = true

[functions.provision-user-cancel]
verify_jwt = true
