-- Placeholder / documentación para la función de vectorización del bucket ai-knowledge.
-- La UI en /dev/lead/ai-vectors llama a: supabase.rpc('vectorize_ai_knowledge_file', { file_path: path })
--
-- Debes implementar esta función (o una Edge Function) que:
-- 1. Lea el archivo del bucket 'ai-knowledge' en la ruta file_path
-- 2. Extraiga texto (según tipo: pdf, txt, etc.)
-- 3. Trocee el contenido en chunks
-- 4. Genere embeddings (p. ej. con pgvector + openai_embed o servicio externo)
-- 5. Inserte/actualice filas en ai_global_vectors con:
--    source_bucket = 'ai-knowledge', source_path = file_path, source_type, chunk_index, content, embedding
--
-- Ejemplo de firma (PostgreSQL):
--
-- CREATE OR REPLACE FUNCTION vectorize_ai_knowledge_file(file_path text)
-- RETURNS jsonb
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- AS $$
-- BEGIN
--   -- Eliminar vectores existentes de este archivo
--   DELETE FROM public.ai_global_vectors
--   WHERE source_bucket = 'ai-knowledge' AND source_path = file_path;
--   -- Aquí: obtener contenido del storage (vía extensions.http o Edge Function),
--   -- chunkear, generar embeddings, insertar en ai_global_vectors.
--   RETURN jsonb_build_object('ok', true, 'path', file_path);
-- END;
-- $$;
